import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Refloat',
  description: 'Terms and conditions for using Refloat.',
};

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--text)', padding: '60px 20px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>

        <Link href="/" style={{ fontSize: 13, color: 'var(--text3)', textDecoration: 'none', display: 'inline-block', marginBottom: 32 }}>
          ← Back
        </Link>

        <h1 style={{ fontFamily: 'var(--font-space-grotesk), sans-serif', fontWeight: 700, fontSize: 32, letterSpacing: '-0.03em', margin: '0 0 8px' }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: 'var(--text3)', margin: '0 0 48px' }}>
          Last updated: April 2026
        </p>

        {[
          {
            title: '1. Acceptance',
            body: `By creating an account and using Refloat, you agree to these Terms of Service. If you do not agree, do not use the service.`,
          },
          {
            title: '2. Description of service',
            body: `Refloat provides AI-generated business health scores and insights for Indian MSMEs using Google Places data and your uploaded POS sales data. Insights are generated by an AI model and are advisory in nature — they do not constitute financial, legal, or professional advice.`,
          },
          {
            title: '3. Your account',
            body: `You must provide accurate information when signing up. You are responsible for all activity under your account. You must be at least 18 years old and legally authorised to operate the business you register.`,
          },
          {
            title: '4. Your data',
            body: `You retain ownership of all business and sales data you upload. By uploading data, you grant Refloat a limited licence to process it solely for the purpose of generating your health scores and insights.`,
          },
          {
            title: '5. Acceptable use',
            body: `You agree not to misuse the service, attempt to reverse-engineer our algorithms, upload false or misleading data, or use the service for any unlawful purpose.`,
          },
          {
            title: '6. Accuracy of insights',
            body: `AI-generated insights are based on available data and may not reflect the full picture of your business. We make no guarantees about the accuracy, completeness, or fitness of insights for any particular purpose. Always apply your own judgement before acting on any recommendation.`,
          },
          {
            title: '7. Limitation of liability',
            body: `Refloat is provided "as is" without warranties of any kind. We are not liable for any direct, indirect, or consequential losses arising from your use of the service or reliance on generated insights.`,
          },
          {
            title: '8. Termination',
            body: `We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time by contacting us.`,
          },
          {
            title: '9. Changes to terms',
            body: `We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms. We will notify registered users of material changes by email.`,
          },
          {
            title: '10. Contact',
            body: `For questions about these terms, email us at legal@refloat.in.`,
          },
        ].map((section) => (
          <div key={section.title} style={{ marginBottom: 36 }}>
            <h2 style={{ fontFamily: 'var(--font-space-grotesk), sans-serif', fontWeight: 600, fontSize: 16, letterSpacing: '-0.01em', margin: '0 0 10px', color: 'var(--text)' }}>
              {section.title}
            </h2>
            <p style={{ fontSize: 14, color: 'var(--text2)', lineHeight: 1.75, margin: 0 }}>
              {section.body}
            </p>
          </div>
        ))}

        <div style={{ borderTop: '1px solid var(--border)', paddingTop: 24, marginTop: 48 }}>
          <p style={{ fontSize: 12, color: 'var(--text3)', margin: 0 }}>
            Refloat — AI-powered business health insights for Indian MSMEs ·{' '}
            <Link href="/privacy" style={{ color: 'var(--text3)', textDecoration: 'underline' }}>Privacy Policy</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
